apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240208112415.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240208112415.0.0+build.6aff574
  releaseNotes: |
    Release v20240208112415.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-05-02-2024-05-47-32-844651453/where-for-dinner-my-apps-bundle@sha256:96ef134c7778363198ea6783cdcae82f3ff7aca85b3f84abf2ac9abe50308279
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

